const Map<String, String> ar = {
  "Update Password":"تحديث الرمز السري",
  'Password':'الرمز السري',
  'Re-Password':'اعادة الرمز السري',
  "Save":"حفظ",
  "What is your phone number?":"ما هو رقم الهاتف الخاص بك؟",
  "Tap Get Started to get an SMS confirmation to help you use OTP. We would like your phone number.":"انقر فوق البدء للحصول على تأكيد عبر الرسائل القصيرة لمساعدتك في استخدام OTP. نود رقم هاتفك.",
  "Phone Number":"رقم الهاتف",
  "Phone cannot be empty":"رقم الهاتف فارغ",
  "Next":"التالي",
  "phoneNumber Not Valid":"رقم الهاتف غير صحيح",
  "Login":"تسجيل الدخول",
  'Email':'البريد الالكتروني',
  'Forget Password?':'هل نسيت كلمة السر',
  "Sign up":"انشاء حساب",
  'First name':'الاسم الاول',
  'Last name':'الاسم الاخير',
  "Date of birth":"تاريخ الميلاد",
  "Car info":"معلومات المركبة",
  "ID number":"رقم الهوية",
  "Sequence number":"الرقم التسلسلي",
  'حروف':'letters',
  'أرقام':'أرقام',
  'Driving license from front':'رخصة القيادة من الامام',
  'edit':'تعديل',
  'driving license from behind':'رخصة القيادة من الخلف',
  "not_sentenced":"عدم محكومية",
  'Medical examination':'الفحص الطبي',
  'License plate':'لوحة المركبة',
  'Car insurance':'تامين المركبة',
  'Driving license':'رخصة القيادة',
  "accept_terms":"الموافقة على شروط الخدمة والخصوصية.",
  'Your request has been sent successfully, we will inform you once it\'s confirmed':'تم ارسال طلبك بنجاح سوف نقوم باخبارك فور الموافقة عليه',
  "Register":"تسجيل",
  "phone authentication":"مصادقة الهاتف",
  "We send code to you to verify your account, please enter code that received to your mobile number.":"لقد قمنا برسال رسالة نصية اليك لتحقق من حسابك يرجي ادخال الكود",
  'Resend':'اعادة الارسال',
  "Resend Code Within":"اعادة الارسال خلال ",
  "Order":"طلب",
  "Your order":"طلبك",
  "has been success":"لقد تم بنجاح",
  "We appreciate your effort":"نحن نشكر جهودك",
  "Confirm":"تأكيد ",
  "Order History":"سجل الطلبات",
  "You have new order!\nTap for info":"لديك طلب جديد\n اضغط للمزيد",
  'Are you sure do want to make your status offline! you will not be able to receive orders until you back online again.':'هل انت متاكد من جعل الحالة الخاصة بك غير متصل ، ذلك يجعلك غير قادر علي استلام الطلبات حتي العودة الي متصل مرة اخرى.',
  'Yes':'نعم',
  'No':'لا',
  "Online":"متصل",
  "Offline":"غير متصل",
  "Notifications":"الاشعارات",
  'write':'اكتب',
  'Send':'ارسال',
  "Pickup information":"معلومات الالتقاط",
  "Map it":"انتقل للوجهة",
  "Delivery information":"معلومات التوصيل",
  "Order information": "معلومات الطلب",
  "Payment Method":"طريقة الدفع",
  "Total Price":"السعر النهائي",
  'Please wait..':'يرجى الانتظار..',
  "Reject":"رفض",
  "Accept":"قبول",
  "New Order!": "طلب جديد!",
  "From":"من",
  "To":"الى",
  "Total orders:":"عدد الطلبات: ",
  "Total collected money:":"مجموع المبالغ المستلمة:",
  "Total amount:":"الرصيد الكلي",
  "Home page":"الصفحة الرئيسية",
  "Payment":"الدفع",
  "Orders history":"سجل الطلبات",
  "Settings":"الاعدادات",
  "Logout":"تسجيل الخروج",
  'Are you sure do want to logout?':'هل انت متاكد من تسجيل الخروج؟',
  'Are you sure do want to delete your account?':'هل انت متاكد من مسح بيانات حسابك؟',
  'Delete my account':'حذف بيانات حسابي',
  "Pickup:":"الالتقاط:",
  "Drop off:":"التسليم:",
  "Status:":"الحالة:",
  "Payment method:":"طريقة الدفع:",
  'Credit cards': "بطاقات الائتمان",
  'Delete card':'حذف البطاقة',
  'Cancel':'إلغاء',
  "delete credit card":'حذف البطاقة الائتمانية',
  "are you sure deleting credit card":'هل انت متأكد من حذف البطاقة؟',
  "No Credit card":'لا يوجد بطاقة دفع',
  "Add new card":"أضف بطاقة جديدة",
  "number":"رقم",
  "expired date":'تاريخ الانتهاء',
  "cvv":"رقم الكود ",
  "card holder name":'إسم صاحب البطاقة',
  "check":"تحقق",
  "invalid card":'خطأ بالبطاقة',
  "Invalid Credit card info":'معلومات البطاقة غير صحيحة',
  "Update info":"تعديل البيانات",
  "Change password":"تعديل الرمز السري",
  "Language":"اللغة",
  "Address":"العنوان",
  "Current Password":"الرمز الحالي",
  "New Password":"الرمز الجديد",
  "Re-new Password":"اعادة الرمز الجديد"
};
