const Map<String, String> en = {
  "Update Password":"Update Password",
  'Password':'Password',
  'Re-Password':'Re-Password',
  "Save":"Save",
  "What is your phone number?":"What is your phone number?",
  "Tap Get Started to get an SMS confirmation to help you use OTP. We would like your phone number.":"Tap Get Started to get an SMS confirmation to help you use OTP. We would like your phone number.",
  "Phone Number":"Phone Number",
  "Phone cannot be empty":"Phone cannot be empty",
  "Next":"Next",
  "phoneNumber Not Valid":"phoneNumber Not Valid",
  "Login":"Login",
  'Email':'Email',
  'Forget Password?':'Forget Password?',
  "Sign up":"Sign up",
  'First name':'First name',
  'Last name':'Last name',
  "Date of birth":"Date of birth",
  "Car info":"Car info",
  "ID number":"ID number",
  "Sequence number":"Sequence number",
  'حروف':'letters',
  'أرقام':'numbers',
  'Driving license from front':'Driving license from front',
  'edit':'Edit',
  'driving license from behind':'Driving license from behind',
  "not_sentenced":"Not Sentenced",
  'Medical examination':'Medical examination',
  'License plate':'License plate',
  'Car insurance':'Car insurance',
  'Driving license':'Driving license',
  // "accept_terms":"الموافقة على شروط الخدمة والخصوصية.",
  "accept_terms":"Accept terms and privacy policy.",
  'Your request has been sent successfully, we will inform you once it\'s confirmed':'Your request has been sent successfully, we will inform you once it\'s confirmed',
  "Register":"Register",
  "phone authentication":"Phone authentication",
  "We send code to you to verify your account, please enter code that received to your mobile number.":"We send code to you to verify your account, please enter code that received to your mobile number.",
  'Resend':'Resend',
  "Resend Code Within":"Resend Code Within",
  "Order":"Order",
  "Your order":"Your order",
  "has been success":"has been success",
  "We appreciate your effort":"We appreciate your effort",
  "Confirm":"Confirm",
  "Order History":"Order History",
  "You have new order!\nTap for info":"You have new order!\nTap for info",
  'Are you sure do want to make your status offline! you will not be able to receive orders until you back online again.':'Are you sure do want to make your status offline! you will not be able to receive orders until you back online again.',
  'Yes':'Yes',
  'No':'No',
  "Online":"Online",
  "Offline":"Offline",
  "Notifications":"Notifications",
  'write':'Write',
  'Send':'Send',
  "Pickup information":"Pickup information",
  "Map it":"Map it",
  "Delivery information":"Delivery information",
  "Order information": "Order information",
  "Payment Method":"Payment Method",
  "Total Price":"Total Price",
  'Please wait..':'Please wait..',
  "Reject":"Reject",
  "Accept":"Accept",
  "New Order!": "New Order!",
  "From":"From",
  "To":"To",
  "Total orders:":"Total orders:",
  "Total collected money:":"Total collected money:",
  "Total amount:":"Total amount:",
  "Home page":"Home page",
  "Payment":"Payment",
  "Orders history":"Orders history",
  "Settings":"Settings",
  "Logout":"Logout",
  'Are you sure do want to logout?':'Are you sure do want to logout?',
  'Are you sure do want to delete your account?':'Are you sure do want to delete your account?',
  'Delete my account':'Delete my account',
  "Pickup:":"Pickup:",
  "Drop off:":"Drop off:",
  "Status:":"Status:",
  "Payment method:":"Payment method:",
  'Credit cards':'Credit cards',
  'Delete card':'Delete card',
  'Cancel':'Cancel',
  "delete credit card":'Delete credit card',
  "are you sure deleting credit card":'Are you sure deleting credit card?',
  "No Credit card":"No Credit card",
  "Add new card":"Add new card",
  "number":"Number",
  "expired date":'expiry date',
  "cvv":"cvv",
  "card holder name":"card holder name",
  "check":"check",
  "invalid card":"invalid card",
  "Invalid Credit card info": "Invalid Credit card info",
  "Update info":"Update info",
  "Change password":"Change password",
  "Language":"Language",
  "Address":"Address",
  "Current Password":"Current Password",
  "New Password":"New Password",
  "Re-new Password":"Re-new Password",
};
